var categoriesList=[
  {
    icon:'resources/image/category-icons/games.png',
    title:"GAMES",
    pictures:[
      'skarbnik.PNG',
      'smileingshadow.GIF',
      'talkndevil.PNG',
      'calcul.png'
    ],
    link:''
  },
  {
    icon:'resources/image/category-icons/programms.png',
    title:"PROGRAMMS",
    pictures:[
      'Magdalena.png',
      'redscope.PNG',
      'sebastian.PNG'
    ],
    link:''
  },
  {
    title:"DESKTOP APPS",
    icon:"resources/image/category-icons/desktop.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:''
  },
  {
    title:"WEBSITES",
    icon:"resources/image/category-icons/w3.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:''
  },
  {
    title:"MOBILE APPS",
    icon:"resources/image/category-icons/mobile.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:''
  },
  /*{
    title:"DEV PROJECTS",
    icon:"resources/image/category-icons/else.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:''
  },*/
  {
    title:"POEMS",
    icon:"resources/image/category-icons/poetry.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:''
  }
]
