var categoriesList=[
  {
    icon:'resources/image/category-icons/games.png',
    title:"GAMES",
    pictures:[
      'skarbnik.PNG',
      'smileingshadow.GIF',
      'talkndevil.PNG',
      'calcul.png'
    ],
    link:'#category/games',
    text:"scratch bite cut, smileing shadow, POJ_B"
  },
  {
    icon:'resources/image/category-icons/programms.png',
    title:"PROGRAMMS",
    pictures:[
      'Magdalena.png',
      'redscope.PNG',
      'sebastian.PNG'
    ],
    link:'#category/programms',
    text:"Rokita, math-calc, best-class-excerptor"
  },
  {
    title:"DESKTOP APPS",
    icon:"resources/image/category-icons/desktop.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:'#category/desktop',
    text:""
  },
  {
    title:"WEBSITES",
    icon:"resources/image/category-icons/w3.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:'#category/web',
    text:""
  },
  {
    title:"MOBILE APPS",
    icon:"resources/image/category-icons/mobile.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:'#category/mobile',
    text:""
  },
  /*{
    title:"DEV PROJECTS",
    icon:"resources/image/category-icons/else.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:''
  },*/
  {
    title:"DOCS",
    icon:"resources/image/category-icons/poetry.png",
    pictures:[
      'dbjsa.png',
      'dddddddddddddddddddddd.png',
      'jjjj.png',
      'kalkul.PNG'
    ],
    link:'#category/docs',
    text:"Tutoriale, Dokumentacje"
  }
];
loadNext();
