var localizationsSettings={
  places:{
    _index_:{
      animationId:"redlinesInTheDarkness",
      animationIntervalTime:70
    },
    docs:{
      animationId:"redlinesInTheDarkness",
      animationIntervalTime:50
    },
    shop:{
      animationId:"redlinesInTheDarkness",
      animationIntervalTime:70
    },
    search:{
      animationId:"squarePatternShades",
      animationIntervalTime:70
    },
    _unknown_:{
      animationId:"squareNoise",
      animationIntervalTime:70
    }
  }
}
loadNext();
