var socialmediaSettings=[
  {
    icon:"facebook",
    address:"https://www.facebook.com/sarverott/"
  },
  {
    icon:"tumblr",
    address:"http://www.sarverott.tumblr.com/"
  },
  {
    icon:"github",
    address:"https://github.com/Sarverott"
  },
  {
    icon:"youtube",
    address:"https://www.youtube.com/channel/UCc_ftDtaXs2u2rveb3TsnYg"
  }
];
loadNext();
