var vm=new Vue({
    el:"#app",
    methods:{
      photosLoader:function(){
        //getPosts
      },
      postsLoader:function(){

      },
      sendMessage:function(){
        sendFormMessage()
      }
    },
    data:{
      general:generalSettings,
      layout:{
        /*
          HEADER
        */
        header:headerSettings,
        /*
          FOOTER
        */
        footer:footerSettings,
        /*
          CONTENT
        */
        content:{
          slider:sliderSettings,
          /*
            SOCIAL MEDIA
          */
          socialMedia:socialmediaSettings,
          /*
            CONTACT
          */
          contact:{
            phoneNumbers:phoneList,
            emails:emailList,
            contactForm:{
              active:true,
              sendURL:"",
              config:{
                user:"",
                pass:"",
                host:""
              }
            }
          },
          /*
            CATEGORIES
          */
          categories:{
            items:categoriesList,
            elseButton:elsebuttonSettings
          }
        }
      },
      backgroundAnimation:backgroundSettings,
      photos:[],
      posts:[]
    }
  });
loadNext();
