var vm=new Vue({
    el:"#app",
    methods:{
      photosLoader:function(){
        //getPosts
      },
      postsLoader:function(){

      },
      sendMessage:function(){
        sendFormMessage()
      }
    },
    data:{
      general:generalSettings,
      layout:{
        header:headerSettings,
        footer:footerSettings,
        content:{
          about:aboutSettings,
          slider:sliderSettings,
          socialMedia:socialmediaSettings,
          contact:{
            phoneNumbers:phoneList,
            emails:emailList,
            contactForm:{
              active:true,
              sendURL:"",
              config:{
                user:"",
                pass:"",
                host:""
              }
            }
          },
          categories:{
            items:categoriesList,
            elseButton:elsebuttonSettings
          }
        }
      },
      backgroundAnimation:backgroundSettings,
      photos:[],
      posts:[]
    }
  });
loadNext();
